#ifndef __DEFINITIONS_H__
#define __DEFINITIONS_H__

#define DISPLAY_TIME_SPLASH_SCENE 2
#define TRANSITION_TIME 0.5
#define OBSTACLE_SPAWN_FREQUENCY 0.005

#define OBSTACLE_GAP 10
#define LOWER_SCREEN_OBSTACLE_THRESH 0.35

#define OBSTACLE_MOVEMENT_SPEED 0.01

#define PROTAG_COLLISION_BITMASK 0x000001
#define OBSTACLE_COLLISION_BITMASK 0x000002
#define GROUND_COLLISION_BITMASK 0x000003

#define PROTAG_FALLING_SPEED 0.0025
#define PROTAG_JUMPING_SPEED 0.00375
#define PROTAG_JUMP_DURATION 0.25
#endif // __DEFINITIONS_H__
